name: My Github Actions

on:
 push:
   branches:
   - main

jobs:
 build:
   runs-on: self-hosted

   strategy:
       matrix:
          python-version: [3.8,3.9]

   steps:
   - name: check code
     uses: actions/checkout@v1

   - name: set up python
     uses: actions/setup-python@v2
     with:
       python-version: ${{ matrix.python-version }}

   - name: Install Dependencies
     run: |
       python -m pip install --upgrade pip
       pip install pytest

   - name: Run Test
     run: |
       cd src
       python -m pytest adition.py
     
